### ISSUE TITLE
Create LongestPalindromicSubstring.cpp

### ISSUE THREAD

**Issue by shivanshuman021** [Rishabh062/Hacktoberfest2021#180]
Pull Request : #178 

I propose to add solution of longest palindromic substring problem . Please assign this issue to me

**Comment by AbhayG01** [comment]
I have good knowledge of Data Structures and Algorithms, please assign this issue to me.

**Comment by neetisaharan13** [comment]
please assign this issue to me.

**Comment by Rishabh062** [comment]
I already got this program. Think something else @shivanshuman021 @AbhayG01 @neetisaharan13
