### ISSUE TITLE
Cpp : To calculate the power of number using recursion

### ISSUE THREAD

**Issue by Ritikakatoch0128** [Rishabh062/Hacktoberfest2021#205]
Hey @Rishabh062 ,
I am participating in #Hactoberfest and want to contribute a code to find the power of number using recursion.
Kindly assign this issue to me.

**Comment by neetisaharan13** [comment]
please assign this issue to me.

**Comment by madhurmehta007** [comment]
Please assign this to me

**Comment by ArkajyotiChakraborty** [comment]
Hey, can you assigned this to me.
