### ISSUE TITLE
Egg-dropping problem

### ISSUE THREAD

**Issue by meghna750** [Rishabh062/Hacktoberfest2021#209]
Hello @Rishabh062 ,
I hope you are going very well. I am participating in hacktoberfest 2021 and want to add the "EGG-DROPPING-PROBLEM" in your repo. This problem is a well-known example of how dynamic programming makes things easier. I will solve it using recursion and dynamic programming both. I will make sure that the reader understands each and every line of my code. 
Please assign this issue to me.
Thanks.

**Comment by Rishabh062** [comment]
That's so nice. Go for it @meghna750 .

**Comment by meghna750** [comment]
Hello @Rishabh062  ,
Thank you for assigning the task to me.
I have made an attempt to solve the "EGG-DROPPING-PROBLEM"  here #223  . I request you to please review it and let me know if anything else needs to be done!
Thanks.

**Comment by Rishabh062** [comment]
Ya sure
