### ISSUE TITLE
Divide two integers (using bit manipulation)

### ISSUE THREAD

**Issue by meghna750** [Rishabh062/Hacktoberfest2021#270]
Hello @Rishabh062 ,
I hope you are going very well. I am participating in hacktoberfest 2021. I would like to contribute more in your repo by adding the question "Divide Two integers Without Using Multiplication, Division, and Modulus Operator", I will solve this using bit manipulation. I assure that I will write well commented and justified code. The reader will understand every line of my code.

Please assign this issue to me.

Thanks.

**Comment by Rishabh062** [comment]
Go for it.
