### ISSUE TITLE
Triplets with bitwise and equal to 0

### ISSUE THREAD

**Issue by meghna750** [Rishabh062/Hacktoberfest2021#272]
hello @Rishabh062 ,
I would like to add the famous problem  "Triplets with Bitwise and equal to 0" in your repo. This problem is considered a hard problem and can be solved by bit manipulation. I observed that the number of questions related to bit manipulation is comparatively less in your repo. I will surely add more interesting problems and will try my best to bring positive changes to your repo!.
I assure you that my code will be completely beginner-friendly, well commented and justified.
Please assign this issue to me.
Thanks.

**Comment by arwazkhan189** [comment]
Ok, go for it
