### ISSUE TITLE
Implement "Stock Span problem" in C++.

### ISSUE THREAD

**Issue by archana-9430** [Rishabh062/Hacktoberfest2021#315]
The stock span is a financial problem, where we need calculate span of stock's price for n days.

**Comment by archana-9430** [comment]
Assign this issue to me, I'll implement this.

**Comment by rishiraj001** [comment]
Assign the issue to me i will write the code as well as explanation line by line.

**Comment by maanya268** [comment]
Please assign it to me.

**Comment by ankur7864** [comment]
Sir please Assign the issue to me
