### ISSUE TITLE
Vending Drink Machine Code implementation in c++

### ISSUE THREAD

**Issue by PurviBhoyar21** [Rishabh062/Hacktoberfest2021#68]
Hey @Rishabh062 
I am a contributor under hacktoberfest 2021.
I can add a c++ code for Vending Drink Machine 
This will be an interesting way to implement  the various concepts of c++ in a single .cpp file
Please assign me this 

Thank you

**Comment by Rishabh062** [comment]
Go for it. Don't forget to add problem statement and comments, so that everyone can understand what is happening.

**Comment by PurviBhoyar21** [comment]
yeah sure

but where's the hacktoberfest2021 label here?
Please give a confirmation

**Comment by Meghwantsingh** [comment]
Hello, I'm new to   hacktoberfest  but i can contribute  sorting or searching C++ related programs .
