### ISSUE TITLE
Stack Sequence Finder

### ISSUE THREAD

**Issue by suvanbalu** [Rishabh062/Hacktoberfest2021#81]
Hey @Rishabh062 
Can you assign me this issue to create a stack sequence finder using python 
So that I can contribute to Hacktoberfest 2021

**Comment by Rishabh062** [comment]
Go for it and generate a pull request

**Comment by suvanbalu** [comment]
Hey @Rishabh062 I have opened a pull request for this issue. Do check it!!!
