### ISSUE TITLE
Matrix Multiplication

### ISSUE THREAD

**Issue by MD571** [Rishabh062/Hacktoberfest2021#873]
Please assign to me

**Comment by ankit0802** [comment]
Please give this task to me ,i am a newbie this would be my first PR in Hacktoberfest

**Comment by STRIZERORTIX** [comment]
I have already created a pull request regarding this Issue. Please Accept

**Comment by Natashaj02** [comment]
Hi! I would like to work on this, Please do assign me this issue.

**Comment by Anshika91** [comment]
hello sir please assign me task i am able to complete it
